import type { LineageChartEdge, LineageChartNode } from "@/components/shared/charts/lineage-chart"

export type PropheticNodeData = {
    honorific: string
    nameEnglish: string
    relation: string
    era: string
    lifespan: string
    passing: string
    epithet: string
    gloss: string
}

const n = (
    id: string,
    ref: number,
    label: string,
    subtitle: string,
    data: PropheticNodeData
): LineageChartNode<PropheticNodeData> => ({ id, ref, label, subtitle, data })

export const PROPHETIC_NODES: LineageChartNode<PropheticNodeData>[] = [
    n("adam", 1, "Adam", "آدم", {
        nameEnglish: "Adam",
        honorific: "ʿalayhi as-salām",
        relation: "Father of humankind · first prophet",
        era: "Primordial",
        lifespan: "~930 years (trad.)",
        passing: "Death · burial on earth",
        epithet: "Primordial vicegerent",
        gloss: "Taught repentance; covenant begins with consciousness of Allah.",
    }),
    n("idris", 2, "Idrīs", "إدريس", {
        nameEnglish: "Enoch (Idrīs)",
        honorific: "ʿalayhi as-salām",
        relation: "Successor in early civilisation",
        era: "Antediluvian",
        lifespan: "Raised in rank (Qurʾān)",
        passing: "Elevated by Allah (trad.)",
        epithet: "Craft and constancy",
        gloss: "Associated with patient daʿwah before the great flood.",
    }),
    n("nuh", 3, "Nūḥ", "نوح", {
        nameEnglish: "Noah",
        honorific: "ʿalayhi as-salām",
        relation: "Messenger to his people",
        era: "Antediluvian",
        lifespan: "950 years daʿwah (trad.)",
        passing: "After the flood · patriarch of survivors",
        epithet: "Patience under refusal",
        gloss: "Ark as sign; covenant of survival and moral reset.",
    }),
    n("hud", 4, "Hūd", "هود", {
        nameEnglish: "Hud",
        honorific: "ʿalayhi as-salām",
        relation: "ʿĀd — Arab lineage",
        era: "Post-flood",
        lifespan: "Not enumerated in Qurʾān",
        passing: "People destroyed; believers saved",
        epithet: "Witness against ʿĀd",
        gloss: "Monumental arrogance met by wind of justice.",
    }),
    n("salih", 5, "Ṣāliḥ", "صالح", {
        nameEnglish: "Salih",
        honorific: "ʿalayhi as-salām",
        relation: "Thamūd — Arab lineage",
        era: "Post-ʿĀd",
        lifespan: "Not enumerated in Qurʾān",
        passing: "Earthquake after she-camel",
        epithet: "Sign of the she-camel",
        gloss: "Miracle mutilated; collapse of a trading arrogance.",
    }),
    n("ibrahim", 6, "Ibrāhīm", "إبراهيم", {
        nameEnglish: "Abraham",
        honorific: "ʿalayhi as-salām",
        relation: "Patriarch · ḥanīf millah",
        era: "Mesopotamia → Levant",
        lifespan: "Long life (trad.)",
        passing: "Buried in Hebron (trad.)",
        epithet: "Friend of Allah (Khalīl)",
        gloss: "Axis of monotheism; father of prophetic houses.",
    }),
    n("lut", 7, "Lūṭ", "لوط", {
        nameEnglish: "Lot",
        honorific: "ʿalayhi as-salām",
        relation: "Nephew of Ibrāhīm",
        era: "Cities of the Plain",
        lifespan: "—",
        passing: "Saved; cities overturned",
        epithet: "Moral perimeter",
        gloss: "Mission to a people beyond reform in their sin.",
    }),
    n("ismail", 8, "Ismāʿīl", "إسماعيل", {
        nameEnglish: "Ishmael",
        honorific: "ʿalayhi as-salām",
        relation: "Son of Ibrāhīm · Hājar",
        era: "Makkah basin",
        lifespan: "137 years (trad.)",
        passing: "Buried near Kaʿbah (trad.)",
        epithet: "Zamzam · sacrifice",
        gloss: "Ancestor of Arabs; ḥajj rites memorialise his trial.",
    }),
    n("ishaq", 9, "Isḥāq", "إسحاق", {
        nameEnglish: "Isaac",
        honorific: "ʿalayhi as-salām",
        relation: "Son of Ibrāhīm · Sārah",
        era: "Canaan",
        lifespan: "180 years (trad.)",
        passing: "Hebron region (trad.)",
        epithet: "Covenant heir",
        gloss: "Line of Banū Isrāʾīl continues through his house.",
    }),
    n("yaqub", 10, "Yaʿqūb", "يعقوب", {
        nameEnglish: "Jacob (Israel)",
        honorific: "ʿalayhi as-salām",
        relation: "Son of Isḥāq",
        era: "Levant · Egypt sojourn",
        lifespan: "147 years (trad.)",
        passing: "Egypt (trad.)",
        epithet: "Israel in supplication",
        gloss: "Father of twelve tribes; loss and reunion of Yūsuf.",
    }),
    n("yusuf", 11, "Yūsuf", "يوسف", {
        nameEnglish: "Joseph",
        honorific: "ʿalayhi as-salām",
        relation: "Son of Yaʿqūb",
        era: "Egypt",
        lifespan: "110 years (trad.)",
        passing: "Egypt (trad.)",
        epithet: "Sovereignty through trial",
        gloss: "Betrayal, prison, elevation — divine plan manifest.",
    }),
    n("ayub", 12, "Ayyūb", "أيوب", {
        nameEnglish: "Job",
        honorific: "ʿalayhi as-salām",
        relation: "Independent prophet",
        era: "Levant (trad.)",
        lifespan: "Long trial then restoration",
        passing: "—",
        epithet: "Endurance as worship",
        gloss: "Affliction without abandoning tawḥīd.",
    }),
    n("shuayb", 13, "Shuʿayb", "شعيب", {
        nameEnglish: "Shuayb (Jethro)",
        honorific: "ʿalayhi as-salām",
        relation: "Madyan · some link to Mūsā lineage",
        era: "Madyan",
        lifespan: "—",
        passing: "People destroyed for fraud",
        epithet: "Measure and market ethics",
        gloss: "Commerce without justice invites collapse.",
    }),
    n("musa", 14, "Mūsā", "موسى", {
        nameEnglish: "Moses",
        honorific: "ʿalayhi as-salām",
        relation: "Banū Isrāʾīl · raised in Pharaoh’s court",
        era: "Egypt → Sinai",
        lifespan: "120 years (trad.)",
        passing: "Beyond Jordan (trad.)",
        epithet: "Kalīm — spoken to directly",
        gloss: "Torah revealed; exodus from tyranny.",
    }),
    n("harun", 15, "Hārūn", "هارون", {
        nameEnglish: "Aaron",
        honorific: "ʿalayhi as-salām",
        relation: "Brother of Mūsā",
        era: "Exodus generation",
        lifespan: "Died before entry (trad.)",
        passing: "Mount Hōr (trad.)",
        epithet: "Voice at the mount",
        gloss: "Supported Mūsā when the calf threatened apostasy.",
    }),
    n("dawud", 16, "Dāwūd", "داود", {
        nameEnglish: "David",
        honorific: "ʿalayhi as-salām",
        relation: "King-prophet · Banū Isrāʾīl",
        era: "Jerusalem",
        lifespan: "100 years (trad.)",
        passing: "Jerusalem (trad.)",
        epithet: "Zabūr and just rule",
        gloss: "Psalms; iron softened by divine permission.",
    }),
    n("sulayman", 17, "Sulaymān", "سليمان", {
        nameEnglish: "Solomon",
        honorific: "ʿalayhi as-salām",
        relation: "Son of Dāwūd",
        era: "United monarchy",
        lifespan: "Reign ~40 years (trad.)",
        passing: "Jerusalem (trad.)",
        epithet: "Wind · jinn · wisdom",
        gloss: "Kingdom in service of tawḥīd, not vanity.",
    }),
    n("ilyas", 18, "Ilyās", "إلياس", {
        nameEnglish: "Elijah",
        honorific: "ʿalayhi as-salām",
        relation: "Prophet to Israel",
        era: "Northern kingdom",
        lifespan: "—",
        passing: "Raised (trad.)",
        epithet: "Against Baʿl",
        gloss: "Restored worship where royal idolatry prevailed.",
    }),
    n("yasa", 19, "al-Yasaʿ", "اليسع", {
        nameEnglish: "Elisha",
        honorific: "ʿalayhi as-salām",
        relation: "Successor of Ilyās",
        era: "Levant",
        lifespan: "—",
        passing: "—",
        epithet: "Successor luminosity",
        gloss: "Continuity of reform in the same region.",
    }),
    n("yunus", 20, "Yūnus", "يونس", {
        nameEnglish: "Jonah",
        honorific: "ʿalayhi as-salām",
        relation: "Messenger to Nineveh",
        era: "Assyria",
        lifespan: "—",
        passing: "—",
        epithet: "Repentance from the deep",
        gloss: "Left in anger; returned through dhikr in darkness.",
    }),
    n("zakariyya", 21, "Zakariyyā", "زكريا", {
        nameEnglish: "Zechariah",
        honorific: "ʿalayhi as-salām",
        relation: "Guardian of Maryam",
        era: "Second Temple period",
        lifespan: "Old age at heir (trad.)",
        passing: "Martyrdom (trad.)",
        epithet: "Supplication in old age",
        gloss: "Asked for heir while tending the miḥrāb.",
    }),
    n("yahya", 22, "Yaḥyā", "يحيى", {
        nameEnglish: "John (the Baptist)",
        honorific: "ʿalayhi as-salām",
        relation: "Son of Zakariyyā",
        era: "Roman Palestine",
        lifespan: "Young · ascetic",
        passing: "Martyrdom (trad.)",
        epithet: "Ascetic witness",
        gloss: "Pure from birth; discipline before ʿĪsā.",
    }),
    n("isa", 23, "ʿĪsā", "عيسى", {
        nameEnglish: "Jesus",
        honorific: "ʿalayhi as-salām",
        relation: "Son of Maryam · Rūḥ from Allah",
        era: "Roman Palestine",
        lifespan: "Ministry in youth (trad.)",
        passing: "Raised to Allah · not crucified (Qurʾān)",
        epithet: "Rūḥ and Word",
        gloss: "Injīl revealed; return awaited near the End.",
    }),
    n("muhammad", 24, "Muḥammad", "محمد", {
        nameEnglish: "Muhammad",
        honorific: "ṣallallāhu ʿalayhi wa-sallam",
        relation: "Seal of prophets · Quraysh",
        era: "7th c. Arabia",
        lifespan: "63 years",
        passing: "632 CE · Madinah",
        epithet: "Khātam al-anbiyāʾ",
        gloss: "Qurʾān as constitution; mercy to all worlds.",
    }),
]

export const PROPHETIC_EDGES: LineageChartEdge[] = [
    { id: "e1", source: "adam", target: "idris", routing: "orthogonal" },
    { id: "e2", source: "idris", target: "nuh", routing: "orthogonal" },
    { id: "e3", source: "nuh", target: "hud", routing: "orthogonal" },
    { id: "e4", source: "hud", target: "salih", routing: "orthogonal" },
    { id: "e5", source: "salih", target: "ibrahim", routing: "orthogonal" },
    { id: "e6", source: "ibrahim", target: "lut", routing: "smooth" },
    { id: "e7", source: "ibrahim", target: "ismail", routing: "smooth" },
    { id: "e8", source: "ibrahim", target: "ishaq", routing: "smooth" },
    { id: "e9", source: "ishaq", target: "yaqub", routing: "orthogonal" },
    { id: "e10", source: "yaqub", target: "yusuf", routing: "orthogonal" },
    { id: "e11", source: "yusuf", target: "ayub", routing: "orthogonal" },
    { id: "e12", source: "ayub", target: "shuayb", routing: "orthogonal" },
    { id: "e13", source: "shuayb", target: "musa", routing: "orthogonal" },
    { id: "e14", source: "musa", target: "harun", routing: "smooth" },
    { id: "e15", source: "musa", target: "dawud", routing: "orthogonal" },
    { id: "e16", source: "dawud", target: "sulayman", routing: "orthogonal" },
    { id: "e17", source: "sulayman", target: "ilyas", routing: "orthogonal" },
    { id: "e18", source: "ilyas", target: "yasa", routing: "orthogonal" },
    { id: "e19", source: "yasa", target: "yunus", routing: "orthogonal" },
    { id: "e20", source: "yunus", target: "zakariyya", routing: "orthogonal" },
    { id: "e21", source: "zakariyya", target: "yahya", routing: "smooth" },
    { id: "e22", source: "yahya", target: "isa", routing: "orthogonal" },
    { id: "e23", source: "isa", target: "muhammad", routing: "orthogonal" },
]
