export const SurahOrderMap = {
    1: { name: "Al-Fatihah", nameEnglish: "The Opening", revelationOrder: 5 },
    2: { name: "Al-Baqarah", nameEnglish: "The Cow", revelationOrder: 87 },
    3: { name: "Ali Imran", nameEnglish: "Family of Imran", revelationOrder: 89 },
    4: { name: "An-Nisa", nameEnglish: "The Women", revelationOrder: 92 },
    5: { name: "Al-Ma'idah", nameEnglish: "The Table Spread", revelationOrder: 112 },
    6: { name: "Al-An'am", nameEnglish: "The Cattle", revelationOrder: 55 },
    7: { name: "Al-A'raf", nameEnglish: "The Heights", revelationOrder: 39 },
    8: { name: "Al-Anfal", nameEnglish: "The Spoils of War", revelationOrder: 88 },
    9: { name: "At-Tawbah", nameEnglish: "The Repentance", revelationOrder: 113 },
    10: { name: "Yunus", nameEnglish: "Jonah", revelationOrder: 51 },
    11: { name: "Hud", nameEnglish: "Hud", revelationOrder: 52 },
    12: { name: "Yusuf", nameEnglish: "Joseph", revelationOrder: 53 },
    13: { name: "Ar-Ra'd", nameEnglish: "The Thunder", revelationOrder: 96 },
    14: { name: "Ibrahim", nameEnglish: "Abraham", revelationOrder: 72 },
    15: { name: "Al-Hijr", nameEnglish: "The Rocky Tract", revelationOrder: 54 },
    16: { name: "An-Nahl", nameEnglish: "The Bee", revelationOrder: 70 },
    17: { name: "Al-Isra", nameEnglish: "The Night Journey", revelationOrder: 50 },
    18: { name: "Al-Kahf", nameEnglish: "The Cave", revelationOrder: 69 },
    19: { name: "Maryam", nameEnglish: "Mary", revelationOrder: 44 },
    20: { name: "Ta-Ha", nameEnglish: "Ta-Ha", revelationOrder: 45 },
    21: { name: "Al-Anbiya", nameEnglish: "The Prophets", revelationOrder: 73 },
    22: { name: "Al-Hajj", nameEnglish: "The Pilgrimage", revelationOrder: 103 },
    23: { name: "Al-Mu'minun", nameEnglish: "The Believers", revelationOrder: 74 },
    24: { name: "An-Nur", nameEnglish: "The Light", revelationOrder: 102 },
    25: { name: "Al-Furqan", nameEnglish: "The Criterion", revelationOrder: 42 },
    26: { name: "Ash-Shu'ara", nameEnglish: "The Poets", revelationOrder: 47 },
    27: { name: "An-Naml", nameEnglish: "The Ant", revelationOrder: 48 },
    28: { name: "Al-Qasas", nameEnglish: "The Stories", revelationOrder: 49 },
    29: { name: "Al-Ankabut", nameEnglish: "The Spider", revelationOrder: 85 },
    30: { name: "Ar-Rum", nameEnglish: "The Romans", revelationOrder: 84 },
    31: { name: "Luqman", nameEnglish: "Luqman", revelationOrder: 57 },
    32: { name: "As-Sajdah", nameEnglish: "The Prostration", revelationOrder: 75 },
    33: { name: "Al-Ahzab", nameEnglish: "The Confederates", revelationOrder: 90 },
    34: { name: "Saba", nameEnglish: "Sheba", revelationOrder: 58 },
    35: { name: "Fatir", nameEnglish: "Originator", revelationOrder: 43 },
    36: { name: "Ya-Sin", nameEnglish: "Ya Sin", revelationOrder: 41 },
    37: { name: "As-Saffat", nameEnglish: "Those Who Set the Ranks", revelationOrder: 56 },
    38: { name: "Sad", nameEnglish: "Sad", revelationOrder: 38 },
    39: { name: "Az-Zumar", nameEnglish: "The Troops", revelationOrder: 59 },
    40: { name: "Ghafir", nameEnglish: "The Forgiver", revelationOrder: 60 },
    41: { name: "Fussilat", nameEnglish: "Explained in Detail", revelationOrder: 61 },
    42: { name: "Ash-Shura", nameEnglish: "Consultation", revelationOrder: 62 },
    43: { name: "Az-Zukhruf", nameEnglish: "Gold Adornments", revelationOrder: 63 },
    44: { name: "Ad-Dukhan", nameEnglish: "The Smoke", revelationOrder: 64 },
    45: { name: "Al-Jathiyah", nameEnglish: "The Kneeling", revelationOrder: 65 },
    46: { name: "Al-Ahqaf", nameEnglish: "The Wind-Curved Sandhills", revelationOrder: 66 },
    47: { name: "Muhammad", nameEnglish: "Muhammad", revelationOrder: 95 },
    48: { name: "Al-Fath", nameEnglish: "The Victory", revelationOrder: 111 },
    49: { name: "Al-Hujurat", nameEnglish: "The Rooms", revelationOrder: 106 },
    50: { name: "Qaf", nameEnglish: "Qaf", revelationOrder: 34 },
    51: { name: "Adh-Dhariyat", nameEnglish: "The Winnowing Winds", revelationOrder: 67 },
    52: { name: "At-Tur", nameEnglish: "The Mount", revelationOrder: 76 },
    53: { name: "An-Najm", nameEnglish: "The Star", revelationOrder: 23 },
    54: { name: "Al-Qamar", nameEnglish: "The Moon", revelationOrder: 37 },
    55: { name: "Ar-Rahman", nameEnglish: "The Most Merciful", revelationOrder: 97 },
    56: { name: "Al-Waqi'ah", nameEnglish: "The Inevitable", revelationOrder: 46 },
    57: { name: "Al-Hadid", nameEnglish: "The Iron", revelationOrder: 94 },
    58: { name: "Al-Mujadila", nameEnglish: "The Pleading Woman", revelationOrder: 105 },
    59: { name: "Al-Hashr", nameEnglish: "The Exile", revelationOrder: 101 },
    60: { name: "Al-Mumtahanah", nameEnglish: "She That Is To Be Examined", revelationOrder: 91 },
    61: { name: "As-Saff", nameEnglish: "The Ranks", revelationOrder: 109 },
    62: { name: "Al-Jumu'ah", nameEnglish: "Friday", revelationOrder: 110 },
    63: { name: "Al-Munafiqun", nameEnglish: "The Hypocrites", revelationOrder: 104 },
    64: { name: "At-Taghabun", nameEnglish: "Mutual Disillusion", revelationOrder: 108 },
    65: { name: "At-Talaq", nameEnglish: "Divorce", revelationOrder: 99 },
    66: { name: "At-Tahrim", nameEnglish: "Prohibition", revelationOrder: 107 },
    67: { name: "Al-Mulk", nameEnglish: "The Sovereignty", revelationOrder: 77 },
    68: { name: "Al-Qalam", nameEnglish: "The Pen", revelationOrder: 2 },
    69: { name: "Al-Haqqah", nameEnglish: "The Reality", revelationOrder: 78 },
    70: { name: "Al-Ma'arij", nameEnglish: "The Ascending Stairways", revelationOrder: 79 },
    71: { name: "Nuh", nameEnglish: "Noah", revelationOrder: 71 },
    72: { name: "Al-Jinn", nameEnglish: "The Jinn", revelationOrder: 40 },
    73: { name: "Al-Muzzammil", nameEnglish: "The Enshrouded One", revelationOrder: 3 },
    74: { name: "Al-Muddathir", nameEnglish: "The Cloaked One", revelationOrder: 4 },
    75: { name: "Al-Qiyamah", nameEnglish: "The Resurrection", revelationOrder: 31 },
    76: { name: "Al-Insan", nameEnglish: "Man", revelationOrder: 98 },
    77: { name: "Al-Mursalat", nameEnglish: "The Emissaries", revelationOrder: 33 },
    78: { name: "An-Naba", nameEnglish: "The Tidings", revelationOrder: 80 },
    79: { name: "An-Nazi'at", nameEnglish: "Those Who Drag Forth", revelationOrder: 81 },
    80: { name: "Abasa", nameEnglish: "He Frowned", revelationOrder: 24 },
    81: { name: "At-Takwir", nameEnglish: "The Overthrowing", revelationOrder: 7 },
    82: { name: "Al-Infitar", nameEnglish: "The Cleaving", revelationOrder: 82 },
    83: { name: "Al-Mutaffifin", nameEnglish: "Defrauding", revelationOrder: 86 },
    84: { name: "Al-Inshiqaq", nameEnglish: "The Splitting Open", revelationOrder: 83 },
    85: { name: "Al-Buruj", nameEnglish: "The Constellations", revelationOrder: 27 },
    86: { name: "At-Tariq", nameEnglish: "The Morning Star", revelationOrder: 36 },
    87: { name: "Al-A'la", nameEnglish: "The Most High", revelationOrder: 8 },
    88: { name: "Al-Ghashiyah", nameEnglish: "The Overwhelming", revelationOrder: 68 },
    89: { name: "Al-Fajr", nameEnglish: "The Dawn", revelationOrder: 10 },
    90: { name: "Al-Balad", nameEnglish: "The City", revelationOrder: 35 },
    91: { name: "Ash-Shams", nameEnglish: "The Sun", revelationOrder: 26 },
    92: { name: "Al-Layl", nameEnglish: "The Night", revelationOrder: 9 },
    93: { name: "Ad-Duha", nameEnglish: "The Morning Hours", revelationOrder: 11 },
    94: { name: "Ash-Sharh", nameEnglish: "The Relief", revelationOrder: 12 },
    95: { name: "At-Tin", nameEnglish: "The Fig", revelationOrder: 28 },
    96: { name: "Al-Alaq", nameEnglish: "The Clot", revelationOrder: 1 },
    97: { name: "Al-Qadr", nameEnglish: "The Power", revelationOrder: 25 },
    98: { name: "Al-Bayyinah", nameEnglish: "The Clear Proof", revelationOrder: 100 },
    99: { name: "Az-Zalzalah", nameEnglish: "The Earthquake", revelationOrder: 93 },
    100: { name: "Al-Adiyat", nameEnglish: "The Chargers", revelationOrder: 14 },
    101: { name: "Al-Qari'ah", nameEnglish: "The Calamity", revelationOrder: 30 },
    102: { name: "At-Takathur", nameEnglish: "Competition", revelationOrder: 16 },
    103: { name: "Al-Asr", nameEnglish: "Time", revelationOrder: 13 },
    104: { name: "Al-Humazah", nameEnglish: "The Slanderer", revelationOrder: 32 },
    105: { name: "Al-Fil", nameEnglish: "The Elephant", revelationOrder: 19 },
    106: { name: "Quraysh", nameEnglish: "Quraysh", revelationOrder: 29 },
    107: { name: "Al-Ma'un", nameEnglish: "Small Kindnesses", revelationOrder: 17 },
    108: { name: "Al-Kawthar", nameEnglish: "Abundance", revelationOrder: 15 },
    109: { name: "Al-Kafirun", nameEnglish: "The Disbelievers", revelationOrder: 18 },
    110: { name: "An-Nasr", nameEnglish: "Divine Support", revelationOrder: 114 },
    111: { name: "Al-Masad", nameEnglish: "The Palm Fiber", revelationOrder: 6 },
    112: { name: "Al-Ikhlas", nameEnglish: "Sincerity", revelationOrder: 22 },
    113: { name: "Al-Falaq", nameEnglish: "Daybreak", revelationOrder: 20 },
    114: { name: "An-Nas", nameEnglish: "Mankind", revelationOrder: 21 }
} as const;