// Surah list (114 surahs)
export type QuranSurahType = {
    number: number
    nameArabic: string
    nameEnglish: string
    verses: number
    revelation: "Meccan" | "Medinan"
}

// English meaning/translation of surah names (for card subtitle)
export const surahNameMeaning: Record<number, string> = {
    1: "The Opening", 2: "The Cow", 3: "Family of Imran", 4: "The Women", 5: "The Table Spread",
    6: "The Cattle", 7: "The Heights", 8: "The Spoils of War", 9: "The Repentance", 10: "Jonah",
    11: "Hud", 12: "Joseph", 13: "The Thunder", 14: "Abraham", 15: "The Rocky Tract", 16: "The Bee",
    17: "The Night Journey", 18: "The Cave", 19: "Mary", 20: "Ta-Ha", 21: "The Prophets", 22: "The Pilgrimage",
    23: "The Believers", 24: "The Light", 25: "The Criterion", 26: "The Poets", 27: "The Ant", 28: "The Stories",
    29: "The Spider", 30: "The Romans", 31: "Luqman", 32: "The Prostration", 33: "The Combined Forces", 34: "Sheba",
    35: "The Originator", 36: "Ya-Sin", 37: "Those Who Stand in Ranks", 38: "Sad", 39: "The Troops", 40: "The Forgiver",
    41: "Explained in Detail", 42: "The Consultation", 43: "The Ornaments", 44: "The Smoke", 45: "The Crouching",
    46: "The Wind-Curved Sandhills", 47: "Muhammad", 48: "The Victory", 49: "The Rooms", 50: "Qaf",
    51: "The Winnowing Winds", 52: "The Mount", 53: "The Star", 54: "The Moon", 55: "The Beneficent", 56: "The Inevitable",
    57: "The Iron", 58: "The Pleading Woman", 59: "The Exile", 60: "The Tested", 61: "The Ranks", 62: "The Friday",
    63: "The Hypocrites", 64: "The Mutual Disillusion", 65: "The Divorce", 66: "The Prohibition", 67: "The Sovereignty",
    68: "The Pen", 69: "The Inevitable", 70: "The Ascending Stairways", 71: "Noah", 72: "The Jinn", 73: "The Enshrouded One",
    74: "The Cloaked One", 75: "The Resurrection", 76: "The Man", 77: "The Emissaries", 78: "The Tidings", 79: "The Extractors",
    80: "He Frowned", 81: "The Overthrowing", 82: "The Cleaving", 83: "The Defrauding", 84: "The Splitting Open", 85: "The Constellations",
    86: "The Night-Comer", 87: "The Most High", 88: "The Overwhelming", 89: "The Dawn", 90: "The City", 91: "The Sun",
    92: "The Night", 93: "The Morning Hours", 94: "The Relief", 95: "The Fig", 96: "The Clot", 97: "The Power",
    98: "The Clear Proof", 99: "The Earthquake", 100: "The Courser", 101: "The Striking Calamity", 102: "The Rivalry",
    103: "The Afternoon", 104: "The Traducer", 105: "The Elephant", 106: "Quraysh", 107: "The Small Kindnesses", 108: "The Abundance",
    109: "The Disbelievers", 110: "The Divine Support", 111: "The Palm Fiber", 112: "The Sincerity", 113: "The Daybreak", 114: "Mankind",
}
export const QuranSurahs: QuranSurahType[] = [
    { number: 1, nameArabic: "الفاتحة", nameEnglish: "Al-Fatiha", verses: 7, revelation: "Meccan" },
    { number: 2, nameArabic: "البقرة", nameEnglish: "Al-Baqarah", verses: 286, revelation: "Medinan" },
    { number: 3, nameArabic: "آل عمران", nameEnglish: "Aali Imran", verses: 200, revelation: "Medinan" },
    { number: 4, nameArabic: "النساء", nameEnglish: "An-Nisa", verses: 176, revelation: "Medinan" },
    { number: 5, nameArabic: "المائدة", nameEnglish: "Al-Ma'idah", verses: 120, revelation: "Medinan" },
    { number: 6, nameArabic: "الأنعام", nameEnglish: "Al-An'am", verses: 165, revelation: "Meccan" },
    { number: 7, nameArabic: "الأعراف", nameEnglish: "Al-A'raf", verses: 206, revelation: "Meccan" },
    { number: 8, nameArabic: "الأنفال", nameEnglish: "Al-Anfal", verses: 75, revelation: "Medinan" },
    { number: 9, nameArabic: "التوبة", nameEnglish: "At-Tawbah", verses: 129, revelation: "Medinan" },
    { number: 10, nameArabic: "يونس", nameEnglish: "Yunus", verses: 109, revelation: "Meccan" },
    { number: 11, nameArabic: "هود", nameEnglish: "Hud", verses: 123, revelation: "Meccan" },
    { number: 12, nameArabic: "يوسف", nameEnglish: "Yusuf", verses: 111, revelation: "Meccan" },
    { number: 13, nameArabic: "الرعد", nameEnglish: "Ar-Ra'd", verses: 43, revelation: "Medinan" },
    { number: 14, nameArabic: "إبراهيم", nameEnglish: "Ibrahim", verses: 52, revelation: "Meccan" },
    { number: 15, nameArabic: "الحجر", nameEnglish: "Al-Hijr", verses: 99, revelation: "Meccan" },
    { number: 16, nameArabic: "النحل", nameEnglish: "An-Nahl", verses: 128, revelation: "Meccan" },
    { number: 17, nameArabic: "الإسراء", nameEnglish: "Al-Isra", verses: 111, revelation: "Meccan" },
    { number: 18, nameArabic: "الكهف", nameEnglish: "Al-Kahf", verses: 110, revelation: "Meccan" },
    { number: 19, nameArabic: "مريم", nameEnglish: "Maryam", verses: 98, revelation: "Meccan" },
    { number: 20, nameArabic: "طه", nameEnglish: "Taha", verses: 135, revelation: "Meccan" },
    { number: 21, nameArabic: "الأنبياء", nameEnglish: "Al-Anbiya", verses: 112, revelation: "Meccan" },
    { number: 22, nameArabic: "الحج", nameEnglish: "Al-Hajj", verses: 78, revelation: "Medinan" },
    { number: 23, nameArabic: "المؤمنون", nameEnglish: "Al-Mu'minun", verses: 118, revelation: "Meccan" },
    { number: 24, nameArabic: "النور", nameEnglish: "An-Nur", verses: 64, revelation: "Medinan" },
    { number: 25, nameArabic: "الفرقان", nameEnglish: "Al-Furqan", verses: 77, revelation: "Meccan" },
    { number: 26, nameArabic: "الشعراء", nameEnglish: "Ash-Shu'ara", verses: 227, revelation: "Meccan" },
    { number: 27, nameArabic: "النمل", nameEnglish: "An-Naml", verses: 93, revelation: "Meccan" },
    { number: 28, nameArabic: "القصص", nameEnglish: "Al-Qasas", verses: 88, revelation: "Meccan" },
    { number: 29, nameArabic: "العنكبوت", nameEnglish: "Al-Ankabut", verses: 69, revelation: "Meccan" },
    { number: 30, nameArabic: "الروم", nameEnglish: "Ar-Rum", verses: 60, revelation: "Meccan" },
    { number: 31, nameArabic: "لقمان", nameEnglish: "Luqman", verses: 34, revelation: "Meccan" },
    { number: 32, nameArabic: "السجدة", nameEnglish: "As-Sajdah", verses: 30, revelation: "Meccan" },
    { number: 33, nameArabic: "الأحزاب", nameEnglish: "Al-Ahzab", verses: 73, revelation: "Medinan" },
    { number: 34, nameArabic: "سبأ", nameEnglish: "Saba", verses: 54, revelation: "Meccan" },
    { number: 35, nameArabic: "فاطر", nameEnglish: "Fatir", verses: 45, revelation: "Meccan" },
    { number: 36, nameArabic: "يس", nameEnglish: "Ya-Sin", verses: 83, revelation: "Meccan" },
    { number: 37, nameArabic: "الصافات", nameEnglish: "As-Saffat", verses: 182, revelation: "Meccan" },
    { number: 38, nameArabic: "ص", nameEnglish: "Sad", verses: 88, revelation: "Meccan" },
    { number: 39, nameArabic: "الزمر", nameEnglish: "Az-Zumar", verses: 75, revelation: "Meccan" },
    { number: 40, nameArabic: "غافر", nameEnglish: "Ghafir", verses: 85, revelation: "Meccan" },
    { number: 41, nameArabic: "فصلت", nameEnglish: "Fussilat", verses: 54, revelation: "Meccan" },
    { number: 42, nameArabic: "الشورى", nameEnglish: "Ash-Shura", verses: 53, revelation: "Meccan" },
    { number: 43, nameArabic: "الزخرف", nameEnglish: "Az-Zukhruf", verses: 89, revelation: "Meccan" },
    { number: 44, nameArabic: "الدخان", nameEnglish: "Ad-Dukhan", verses: 59, revelation: "Meccan" },
    { number: 45, nameArabic: "الجاثية", nameEnglish: "Al-Jathiyah", verses: 37, revelation: "Meccan" },
    { number: 46, nameArabic: "الأحقاف", nameEnglish: "Al-Ahqaf", verses: 35, revelation: "Meccan" },
    { number: 47, nameArabic: "محمد", nameEnglish: "Muhammad", verses: 38, revelation: "Medinan" },
    { number: 48, nameArabic: "الفتح", nameEnglish: "Al-Fath", verses: 29, revelation: "Medinan" },
    { number: 49, nameArabic: "الحجرات", nameEnglish: "Al-Hujurat", verses: 18, revelation: "Medinan" },
    { number: 50, nameArabic: "ق", nameEnglish: "Qaf", verses: 45, revelation: "Meccan" },
    { number: 51, nameArabic: "الذاريات", nameEnglish: "Adh-Dhariyat", verses: 60, revelation: "Meccan" },
    { number: 52, nameArabic: "الطور", nameEnglish: "At-Tur", verses: 49, revelation: "Meccan" },
    { number: 53, nameArabic: "النجم", nameEnglish: "An-Najm", verses: 62, revelation: "Meccan" },
    { number: 54, nameArabic: "القمر", nameEnglish: "Al-Qamar", verses: 55, revelation: "Meccan" },
    { number: 55, nameArabic: "الرحمن", nameEnglish: "Ar-Rahman", verses: 78, revelation: "Medinan" },
    { number: 56, nameArabic: "الواقعة", nameEnglish: "Al-Waqi'ah", verses: 96, revelation: "Meccan" },
    { number: 57, nameArabic: "الحديد", nameEnglish: "Al-Hadid", verses: 29, revelation: "Medinan" },
    { number: 58, nameArabic: "المجادلة", nameEnglish: "Al-Mujadila", verses: 22, revelation: "Medinan" },
    { number: 59, nameArabic: "الحشر", nameEnglish: "Al-Hashr", verses: 24, revelation: "Medinan" },
    { number: 60, nameArabic: "الممتحنة", nameEnglish: "Al-Mumtahanah", verses: 13, revelation: "Medinan" },
    { number: 61, nameArabic: "الصف", nameEnglish: "As-Saf", verses: 14, revelation: "Medinan" },
    { number: 62, nameArabic: "الجمعة", nameEnglish: "Al-Jumu'ah", verses: 11, revelation: "Medinan" },
    { number: 63, nameArabic: "المنافقون", nameEnglish: "Al-Munafiqun", verses: 11, revelation: "Medinan" },
    { number: 64, nameArabic: "التغابن", nameEnglish: "At-Taghabun", verses: 18, revelation: "Medinan" },
    { number: 65, nameArabic: "الطلاق", nameEnglish: "At-Talaq", verses: 12, revelation: "Medinan" },
    { number: 66, nameArabic: "التحريم", nameEnglish: "At-Tahrim", verses: 12, revelation: "Medinan" },
    { number: 67, nameArabic: "الملك", nameEnglish: "Al-Mulk", verses: 30, revelation: "Meccan" },
    { number: 68, nameArabic: "القلم", nameEnglish: "Al-Qalam", verses: 52, revelation: "Meccan" },
    { number: 69, nameArabic: "الحاقة", nameEnglish: "Al-Haqqah", verses: 52, revelation: "Meccan" },
    { number: 70, nameArabic: "المعارج", nameEnglish: "Al-Ma'arij", verses: 44, revelation: "Meccan" },
    { number: 71, nameArabic: "نوح", nameEnglish: "Nuh", verses: 28, revelation: "Meccan" },
    { number: 72, nameArabic: "الجن", nameEnglish: "Al-Jinn", verses: 28, revelation: "Meccan" },
    { number: 73, nameArabic: "المزمل", nameEnglish: "Al-Muzzammil", verses: 20, revelation: "Meccan" },
    { number: 74, nameArabic: "المدثر", nameEnglish: "Al-Muddaththir", verses: 56, revelation: "Meccan" },
    { number: 75, nameArabic: "القيامة", nameEnglish: "Al-Qiyamah", verses: 40, revelation: "Meccan" },
    { number: 76, nameArabic: "الإنسان", nameEnglish: "Al-Insan", verses: 31, revelation: "Medinan" },
    { number: 77, nameArabic: "المرسلات", nameEnglish: "Al-Mursalat", verses: 50, revelation: "Meccan" },
    { number: 78, nameArabic: "النبأ", nameEnglish: "An-Naba", verses: 40, revelation: "Meccan" },
    { number: 79, nameArabic: "النازعات", nameEnglish: "An-Nazi'at", verses: 46, revelation: "Meccan" },
    { number: 80, nameArabic: "عبس", nameEnglish: "Abasa", verses: 42, revelation: "Meccan" },
    { number: 81, nameArabic: "التكوير", nameEnglish: "At-Takwir", verses: 29, revelation: "Meccan" },
    { number: 82, nameArabic: "الانفطار", nameEnglish: "Al-Infitar", verses: 19, revelation: "Meccan" },
    { number: 83, nameArabic: "المطففين", nameEnglish: "Al-Mutaffifin", verses: 36, revelation: "Meccan" },
    { number: 84, nameArabic: "الانشقاق", nameEnglish: "Al-Inshiqaq", verses: 25, revelation: "Meccan" },
    { number: 85, nameArabic: "البروج", nameEnglish: "Al-Buruj", verses: 22, revelation: "Meccan" },
    { number: 86, nameArabic: "الطارق", nameEnglish: "At-Tariq", verses: 17, revelation: "Meccan" },
    { number: 87, nameArabic: "الأعلى", nameEnglish: "Al-A'la", verses: 19, revelation: "Meccan" },
    { number: 88, nameArabic: "الغاشية", nameEnglish: "Al-Ghashiyah", verses: 26, revelation: "Meccan" },
    { number: 89, nameArabic: "الفجر", nameEnglish: "Al-Fajr", verses: 30, revelation: "Meccan" },
    { number: 90, nameArabic: "البلد", nameEnglish: "Al-Balad", verses: 20, revelation: "Meccan" },
    { number: 91, nameArabic: "الشمس", nameEnglish: "Ash-Shams", verses: 15, revelation: "Meccan" },
    { number: 92, nameArabic: "الليل", nameEnglish: "Al-Layl", verses: 21, revelation: "Meccan" },
    { number: 93, nameArabic: "الضحى", nameEnglish: "Ad-Duha", verses: 11, revelation: "Meccan" },
    { number: 94, nameArabic: "الشرح", nameEnglish: "Ash-Sharh", verses: 8, revelation: "Meccan" },
    { number: 95, nameArabic: "التين", nameEnglish: "At-Tin", verses: 8, revelation: "Meccan" },
    { number: 96, nameArabic: "العلق", nameEnglish: "Al-Alaq", verses: 19, revelation: "Meccan" },
    { number: 97, nameArabic: "القدر", nameEnglish: "Al-Qadr", verses: 5, revelation: "Meccan" },
    { number: 98, nameArabic: "البينة", nameEnglish: "Al-Bayyinah", verses: 8, revelation: "Medinan" },
    { number: 99, nameArabic: "الزلزلة", nameEnglish: "Az-Zalzalah", verses: 8, revelation: "Medinan" },
    { number: 100, nameArabic: "العاديات", nameEnglish: "Al-Adiyat", verses: 11, revelation: "Meccan" },
    { number: 101, nameArabic: "القارعة", nameEnglish: "Al-Qari'ah", verses: 11, revelation: "Meccan" },
    { number: 102, nameArabic: "التكاثر", nameEnglish: "At-Takathur", verses: 8, revelation: "Meccan" },
    { number: 103, nameArabic: "العصر", nameEnglish: "Al-Asr", verses: 3, revelation: "Meccan" },
    { number: 104, nameArabic: "الهمزة", nameEnglish: "Al-Humazah", verses: 9, revelation: "Meccan" },
    { number: 105, nameArabic: "الفيل", nameEnglish: "Al-Fil", verses: 5, revelation: "Meccan" },
    { number: 106, nameArabic: "قريش", nameEnglish: "Quraysh", verses: 4, revelation: "Meccan" },
    { number: 107, nameArabic: "الماعون", nameEnglish: "Al-Ma'un", verses: 7, revelation: "Meccan" },
    { number: 108, nameArabic: "الكوثر", nameEnglish: "Al-Kawthar", verses: 3, revelation: "Meccan" },
    { number: 109, nameArabic: "الكافرون", nameEnglish: "Al-Kafirun", verses: 6, revelation: "Meccan" },
    { number: 110, nameArabic: "النصر", nameEnglish: "An-Nasr", verses: 3, revelation: "Medinan" },
    { number: 111, nameArabic: "المسد", nameEnglish: "Al-Masad", verses: 5, revelation: "Meccan" },
    { number: 112, nameArabic: "الإخلاص", nameEnglish: "Al-Ikhlas", verses: 4, revelation: "Meccan" },
    { number: 113, nameArabic: "الفلق", nameEnglish: "Al-Falaq", verses: 5, revelation: "Meccan" },
    { number: 114, nameArabic: "الناس", nameEnglish: "An-Nas", verses: 6, revelation: "Meccan" },
]


// Detail page verse mock for Al-Fatihah (used for UI only)
export type QuranVerseType = {
    number: number
    arabic: string
    transliteration: string
    translation: string
}
export const SurahAlFatihahMockVerses: QuranVerseType[] = [
    {
        number: 1,
        arabic: "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
        transliteration: "Bismillāhi r-raḥmāni r-raḥīm",
        translation: "In the name of Allah, the Most Gracious, the Most Merciful.",
    },
    {
        number: 2,
        arabic: "ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ",
        transliteration: "Al-ḥamdu lillāhi rabbi l-ʿālamīn",
        translation: "All praise is due to Allah, Lord of all the worlds.",
    },
    {
        number: 3,
        arabic: "ٱلرَّحْمَٰنِ ٱلرَّحِيمِ",
        transliteration: "Ar-raḥmāni r-raḥīm",
        translation: "The Most Gracious, the Most Merciful.",
    },
    {
        number: 4,
        arabic: "مَٰلِكِ يَوْمِ ٱلدِّينِ",
        transliteration: "Māliki yawmi d-dīn",
        translation: "Master of the Day of Judgment.",
    },
    {
        number: 5,
        arabic: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
        transliteration: "Iyyāka naʿbudu wa iyyāka nastaʿīn",
        translation: "You alone we worship, and You alone we ask for help.",
    },
    {
        number: 6,
        arabic: "ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ",
        transliteration: "Ihdinā ṣ-ṣirāṭa l-mustaqīm",
        translation: "Guide us along the Straight Path,",
    },
    {
        number: 7,
        arabic: "صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ",
        transliteration: "Ṣirāṭa lladhīna anʿamta ʿalayhim ghayri l-maghḍūbi ʿalayhim wa lā ḍ-ḍāllīn",
        translation: "the Path of those You have blessed—not those You are displeased with, or those who are astray.",
    },
]
