export type StoryCategory = { id: string; label: string }

export type StoryTopic = {
    id: string
    title: string
    category: string
    excerpt: string
    readMinutes: number
    prophet: string
    lesson: string
    body: string
    moralPoints: string[]
    quote?: { text: string; source: string }
    /** Tailwind gradient for card + modal header */
    theme: "emerald" | "amber" | "sky" | "rose" | "violet"
}

export const STORIES_EDITORIAL = {
    badge: "Prophetic stories",
    title: "Lessons from the prophets",
    lead: "Real stories from the Quran and Sunnah that teach patience, trust, and good character.",
}

export const STORIES_CATEGORIES: StoryCategory[] = [
    { id: "all", label: "All" },
    { id: "patience", label: "Patience" },
    { id: "trust", label: "Trust in Allah" },
    { id: "family", label: "Family" },
    { id: "courage", label: "Courage" },
]

export const STORY_THEME_STYLES: Record<
    StoryTopic["theme"],
    { card: string; modal: string; pill: string; accent: string }
> = {
    emerald: {
        card: "border-emerald-100 hover:border-emerald-300 from-emerald-50/80",
        modal: "from-emerald-600/90 via-emerald-700/80 to-emerald-900/90",
        pill: "bg-emerald-100 text-emerald-800 ring-emerald-200",
        accent: "text-emerald-600",
    },
    amber: {
        card: "border-amber-100 hover:border-amber-300 from-amber-50/80",
        modal: "from-amber-500/90 via-amber-600/80 to-amber-900/90",
        pill: "bg-amber-100 text-amber-900 ring-amber-200",
        accent: "text-amber-600",
    },
    sky: {
        card: "border-sky-100 hover:border-sky-300 from-sky-50/80",
        modal: "from-sky-500/90 via-sky-600/80 to-sky-900/90",
        pill: "bg-sky-100 text-sky-900 ring-sky-200",
        accent: "text-sky-600",
    },
    rose: {
        card: "border-rose-100 hover:border-rose-300 from-rose-50/80",
        modal: "from-rose-500/90 via-rose-600/80 to-rose-900/90",
        pill: "bg-rose-100 text-rose-900 ring-rose-200",
        accent: "text-rose-600",
    },
    violet: {
        card: "border-violet-100 hover:border-violet-300 from-violet-50/80",
        modal: "from-violet-500/90 via-violet-600/80 to-violet-900/90",
        pill: "bg-violet-100 text-violet-900 ring-violet-200",
        accent: "text-violet-600",
    },
}

export const STORIES_TOPICS: StoryTopic[] = [
    {
        id: "yusuf",
        title: "Yusuf and his brothers",
        category: "patience",
        prophet: "Yusuf عليه السلام",
        excerpt: "Betrayed by family, yet he forgave and rose with honor.",
        lesson: "Honesty and patience can turn deep harm into honor.",
        body: "Yusuf was thrown in a well and sold as a slave. Years later he became a leader in Egypt. When his brothers came hungry, he forgave them. His story teaches that harm is not the end when you stay honest and patient with Allah.",
        moralPoints: ["Forgive when you have power", "Do not boast in victory", "Dreams from Allah need time"],
        quote: { text: "Indeed, he who fears Allah and is patient — then indeed, Allah does not allow to be lost the reward of those who do good.", source: "Quran 12:90" },
        readMinutes: 6,
        theme: "amber",
    },
    {
        id: "ayub",
        title: "Ayub and illness",
        category: "patience",
        prophet: "Ayub عليه السلام",
        excerpt: "Wealth and health left, but his love for Allah stayed.",
        lesson: "Pain can purify the heart when we complain only to Allah.",
        body: "Ayub lost property and suffered for many years. He never cursed Allah. When he was healed, his family returned. The lesson: hardship can purify the heart if we keep doing good.",
        moralPoints: ["Never blame Allah for tests", "Keep worship in pain", "Relief comes by His timing"],
        readMinutes: 4,
        theme: "emerald",
    },
    {
        id: "hajar",
        title: "Hajar and Zamzam",
        category: "trust",
        prophet: "Hajar",
        excerpt: "A mother’s run between two hills became an act of worship.",
        lesson: "Trust Allah after you do your part.",
        body: "Ibrahim left Hajar and baby Ismail in a dry valley by Allah’s command. She searched for water until Zamzam flowed. Today millions walk her path during Hajj. Trust means effort plus tawakkul.",
        moralPoints: ["Effort and trust go together", "Women of faith shape history", "Sabr in loneliness"],
        readMinutes: 4,
        theme: "sky",
    },
    {
        id: "nuh",
        title: "Nuh and the ark",
        category: "courage",
        prophet: "Nuh عليه السلام",
        excerpt: "He called his people for centuries and never gave up.",
        lesson: "Keep calling to good even when results are slow.",
        body: "Nuh preached for hundreds of years. Only a few believed. Allah saved him and the believers in the ark. Mockery did not stop his duty.",
        moralPoints: ["Dawah needs patience", "Stay firm on truth", "Small groups can be saved"],
        readMinutes: 5,
        theme: "violet",
    },
    {
        id: "lut",
        title: "Lut and his guest",
        category: "courage",
        prophet: "Lut عليه السلام",
        excerpt: "He protected strangers when his people chose evil.",
        lesson: "Stand for truth even under pressure.",
        body: "Angels came as guests. His people demanded evil. Lut offered lawful alternatives. Allah destroyed the wicked city. The story warns against shamelessness.",
        moralPoints: ["Protect guests and the weak", "Do not follow the crowd", "Evil societies fall"],
        readMinutes: 5,
        theme: "rose",
    },
    {
        id: "maryam",
        title: "Maryam and her son",
        category: "family",
        prophet: "Maryam & ʿIsa عليهما السلام",
        excerpt: "Chosen for purity and honored in the Quran by name.",
        lesson: "Dignity comes from taqwa, not people’s whispers.",
        body: "Maryam dedicated herself to worship. She bore ʿIsa by Allah’s will. People accused her, but Allah defended her in the Quran.",
        moralPoints: ["Chastity is strength", "Allah defends the truthful", "Trust Him in scandal"],
        quote: { text: "And We made the son of Maryam and his mother a sign.", source: "Quran 23:50" },
        readMinutes: 4,
        theme: "sky",
    },
    {
        id: "ibrahim",
        title: "Ibrahim and the fire",
        category: "trust",
        prophet: "Ibrahim عليه السلام",
        excerpt: "Thrown into fire — Allah said: O fire, be cool and safe.",
        lesson: "When you choose Allah, He chooses your outcome.",
        body: "The tyrant lit a huge fire to burn Ibrahim. Allah cooled it for him. Ibrahim left unharmed. It shows that no plan against Allah’s allies succeeds.",
        moralPoints: ["Tawhid before comfort", "Fear Allah alone", "Tests reveal faith"],
        readMinutes: 4,
        theme: "amber",
    },
    {
        id: "musa-sea",
        title: "Musa and the sea",
        category: "courage",
        prophet: "Musa عليه السلام",
        excerpt: "Pharaoh’s army behind, the sea ahead — then a path opened.",
        lesson: "When there is no way, Allah makes one.",
        body: "Musa and Bani Israil reached the sea with Pharaoh chasing. Allah split the sea. They crossed; Pharaoh drowned. Fear turned to awe of Allah’s power.",
        moralPoints: ["Do not panic at dead ends", "Follow the prophet’s lead", "Arrogance drowns"],
        readMinutes: 5,
        theme: "emerald",
    },
    {
        id: "dawud-goliath",
        title: "Dawud and the giant",
        category: "courage",
        prophet: "Dawud عليه السلام",
        excerpt: "A young man faced a warrior army feared by kings.",
        lesson: "True strength is trust in Allah, not size.",
        body: "Dawud accepted the challenge when others hesitated. He defeated Jalut with a sling and stone. Allah gave him kingdom and wisdom afterward.",
        moralPoints: ["Do not fear bullies", "Skill plus tawakkul wins", "Humility after victory"],
        readMinutes: 4,
        theme: "sky",
    },
    {
        id: "sulayman-ants",
        title: "Sulayman and the ants",
        category: "patience",
        prophet: "Sulayman عليه السلام",
        excerpt: "A king heard the smallest creature warn its colony.",
        lesson: "Power should be gentle and aware of the weak.",
        body: "Sulayman understood the language of ants. He smiled and thanked Allah for the gift. He ordered his army to avoid harming the ant valley.",
        moralPoints: ["Leaders protect the weak", "Thank Allah for gifts", "Avoid arrogance in power"],
        readMinutes: 4,
        theme: "emerald",
    },
    {
        id: "zakariyya-dua",
        title: "Zakariyya's prayer",
        category: "family",
        prophet: "Zakariyya عليه السلام",
        excerpt: "An old man asked Allah for a child and never lost hope.",
        lesson: "Keep asking Allah even when odds seem impossible.",
        body: "Zakariyya prayed privately for an heir. Angels announced Yahya while he was old. His story shows dua at the end of life can still bloom.",
        moralPoints: ["Private dua is beloved", "Hope until the end", "Allah plans beyond biology"],
        readMinutes: 4,
        theme: "rose",
    },
    {
        id: "ismail-sacrifice",
        title: "Ismail and the sacrifice",
        category: "trust",
        prophet: "Ibrahim & Ismail عليهما السلام",
        excerpt: "Father and son submitted when the dream came.",
        lesson: "Submission to Allah comes before comfort.",
        body: "Ibrahim saw he should sacrifice his son. Ismail agreed to obey Allah. Allah replaced him with a ram. Eid al-Adha remembers this trust.",
        moralPoints: ["Family can share faith", "Tests reveal love of Allah", "Obedience brings relief"],
        readMinutes: 5,
        theme: "amber",
    },
    {
        id: "shuayb-merchants",
        title: "Shuʿayb and fair trade",
        category: "courage",
        prophet: "Shuʿayb عليه السلام",
        excerpt: "He warned a wealthy people who cheated in business.",
        lesson: "Honest scales are part of taqwa.",
        body: "His people shortchanged customers and blocked the path of Allah. Shuʿayb called them to fair measure. They rejected him and were destroyed.",
        moralPoints: ["Business ethics matter", "Warn with wisdom", "Greed destroys communities"],
        readMinutes: 4,
        theme: "violet",
    },
    {
        id: "hud-ad",
        title: "Hud and the people of ʿAd",
        category: "courage",
        prophet: "Hud عليه السلام",
        excerpt: "A mighty nation mocked the call to leave idols.",
        lesson: "Strength without faith is fragile.",
        body: "ʿAd boasted of tall buildings and power. Hud invited them to worship Allah alone. They called him a liar. A violent wind ended their pride.",
        moralPoints: ["Do not boast in buildings", "Reject idolatry of ego", "Heed warnings early"],
        readMinutes: 4,
        theme: "sky",
    },
    {
        id: "salih-camel",
        title: "Salih and the she-camel",
        category: "trust",
        prophet: "Salih عليه السلام",
        excerpt: "A miraculous camel became a test for Thamud.",
        lesson: "Signs demand respect, not cruelty.",
        body: "Allah sent a unique camel as proof for Thamud. They were told to share water. They hamstrung her instead. Earthquake seized the wrongdoers.",
        moralPoints: ["Do not harm Allah's signs", "Share resources fairly", "Reject mob cruelty"],
        readMinutes: 4,
        theme: "rose",
    },
    {
        id: "musa-pharaoh",
        title: "Musa in Pharaoh's palace",
        category: "family",
        prophet: "Musa عليه السلام",
        excerpt: "Raised in the house of the tyrant he would confront.",
        lesson: "Allah prepares His servants in hidden ways.",
        body: "Baby Musa was placed in the river and taken into Pharaoh's home. His own mother nursed him. Years later he returned with divine mission.",
        moralPoints: ["Allah plans secretly", "Mothers are protectors", "Tyrants cannot block destiny"],
        readMinutes: 5,
        theme: "emerald",
    },
    {
        id: "dawud-judgment",
        title: "Dawud's fair judgment",
        category: "patience",
        prophet: "Dawud عليه السلام",
        excerpt: "Two disputants taught a king a lesson in hidden bias.",
        lesson: "Leaders must hear every side with justice.",
        body: "Two men came with a dispute over sheep. Dawud ruled quickly then realized his error through a parable. He repented and sought forgiveness.",
        moralPoints: ["Admit mistakes quickly", "Justice needs reflection", "Repentance suits leaders"],
        readMinutes: 4,
        theme: "amber",
    },
    {
        id: "yunus-whale",
        title: "Yunus in the darkness",
        category: "patience",
        prophet: "Yunus عليه السلام",
        excerpt: "He left his people in anger and was swallowed by the whale.",
        lesson: "Never despair of Allah's mercy in the darkest place.",
        body: "Yunus called out from belly of the whale in layered darkness. Allah answered. He returned to his people and they believed.",
        moralPoints: ["Anger can mislead", "La ilaha illa Anta saves", "Return to duty after mistake"],
        readMinutes: 5,
        theme: "violet",
    },
    {
        id: "ibrahim-guests",
        title: "Ibrahim's angel guests",
        category: "family",
        prophet: "Ibrahim عليه السلام",
        excerpt: "Angels came as travelers and brought news of a son.",
        lesson: "Honor guests even when tired.",
        body: "Ibrahim rushed to serve roasted calf to unknown guests. They were angels bearing glad tidings of Ishaq and warning about Lut's people.",
        moralPoints: ["Generosity is prophetic", "Angels test character", "Good news follows service"],
        readMinutes: 4,
        theme: "sky",
    },
    {
        id: "sulayman-bird",
        title: "The missing hoopoe",
        category: "trust",
        prophet: "Sulayman عليه السلام",
        excerpt: "A bird scouted lands the army had not yet seen.",
        lesson: "Curiosity in Allah's cause can uncover truth.",
        body: "The hoopoe reported Queen Bilqis and her sun-worshipping people. Sulayman sent a letter calling to Islam. She later submitted peacefully.",
        moralPoints: ["Investigate before war", "Invite with wisdom", "Truth wins with patience"],
        readMinutes: 5,
        theme: "emerald",
    },
    {
        id: "adam-creation",
        title: "Adam and the angels",
        category: "trust",
        prophet: "Adam عليه السلام",
        excerpt: "The first human taught names and honored above angels.",
        lesson: "Knowledge and repentance define humanity.",
        body: "Allah taught Adam names and asked angels to prostrate. Iblis refused. Adam lived in Jannah, slipped, repented, and was forgiven.",
        moralPoints: ["Learn names and meanings", "Repentance is human strength", "Reject Iblis' pride"],
        readMinutes: 5,
        theme: "amber",
    },
    {
        id: "lut-wife",
        title: "Lut's warning",
        category: "courage",
        prophet: "Lut عليه السلام",
        excerpt: "A prophet's family can still choose the wrong path.",
        lesson: "Belonging to a prophet does not replace personal faith.",
        body: "Lut warned his people against immorality. His wife sympathized with the sinners. Angels destroyed the city while saving Lut and believers.",
        moralPoints: ["Stand with truth alone if needed", "Family ties do not excuse sin", "Flee Allah's punishment"],
        readMinutes: 4,
        theme: "rose",
    },
    {
        id: "isa-table",
        title: "ʿIsa and the table",
        category: "family",
        prophet: "ʿIsa عليه السلام",
        excerpt: "Disciples asked heaven for a feast to strengthen faith.",
        lesson: "Miracles increase responsibility, not casual doubt.",
        body: "Disciples requested a spread from heaven. Allah granted it with a stern warning. The story teaches gratitude after seeing signs.",
        moralPoints: ["Do not demand signs out of stubbornness", "Thank Allah after miracles", "Faith needs follow-through"],
        readMinutes: 4,
        theme: "violet",
    },
    {
        id: "musa-khidr",
        title: "Musa and al-Khidr",
        category: "patience",
        prophet: "Musa عليه السلام",
        excerpt: "A journey where apparent harm hid divine wisdom.",
        lesson: "You may not see the full wisdom behind events.",
        body: "Musa traveled to learn patience. A ship was damaged, a boy died, a wall was repaired. Each act had hidden mercy Khidr explained later.",
        moralPoints: ["Trust scholars of inner wisdom", "Patience with Allah's decree", "Do not judge surface events"],
        readMinutes: 6,
        theme: "sky",
    },
    {
        id: "yaqub-loss",
        title: "Yaqub and the shirt",
        category: "patience",
        prophet: "Yaqub عليه السلام",
        excerpt: "Years of grief ended with a shirt that restored sight.",
        lesson: "Beautiful patience carries through loss.",
        body: "Yaqub lost Yusuf and Binyamin for years. He never despaired of Allah. When Yusuf's shirt came, grief turned to joy and prostration.",
        moralPoints: ["Do not despair of relief", "Complaint is to Allah alone", "Family tests can be long"],
        readMinutes: 5,
        theme: "emerald",
    },
    {
        id: "ilyas-call",
        title: "Ilyas on the mountain",
        category: "courage",
        prophet: "Ilyas عليه السلام",
        excerpt: "He stood against a people who worshipped Baʿl.",
        lesson: "One sincere caller can outlast popular falsehood.",
        body: "Ilyas called Israel to worship Allah alone. He faced royal idolatry. Allah raised Al-Yasa as successor. Truth continues through generations.",
        moralPoints: ["Idolatry returns in new forms", "Mentor the next caller", "Never think you are alone"],
        readMinutes: 4,
        theme: "amber",
    },
    {
        id: "dhul-qarnayn",
        title: "Dhul-Qarnayn and the wall",
        category: "trust",
        prophet: "Dhul-Qarnayn",
        excerpt: "A just ruler helped weak people against Gog and Magog.",
        lesson: "Power used for justice is blessed.",
        body: "He traveled east and west aiding people. Mountain villagers asked help against corruption. He built a barrier with their labor, not arrogance.",
        moralPoints: ["Help the oppressed", "Use resources fairly", "Some evils are delayed, not erased"],
        readMinutes: 5,
        theme: "violet",
    },
]

export function getStoryById(id: string): StoryTopic | undefined {
    return STORIES_TOPICS.find((s) => s.id === id)
}
