// lib/api/consts.ts

// Quran --
export const quranLanguages = [
    "Achinese",
    "Afar",
    "Afrikaans",
    "Albanian",
    "Amharic",
    "Arabic",
    "Assamese",
    "Azerbaijani",
    "Bambara",
    "Bengali",
    "Berber",
    "Bosnian",
    "Bulgarian",
    "Burmese",
    "Catalan",
    "Chichewa",
    "Chinese_Simplified",
    "Chinese_Traditional",
    "Croatian",
    "Czech",
    "Dagbani",
    "Dari",
    "Danish",
    "Divehi",
    "Dutch",
    "English",
    "Esperanto",
    "Filipino",
    "Finnish",
    "French",
    "Fulah",
    "Ganda",
    "German",
    "Gujarati",
    "Hausa",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Indonesian",
    "Iranun",
    "Italian",
    "Japanese",
    "Javanese",
    "Kannada",
    "Kazakh",
    "Kendayan",
    "Khmer",
    "Kinyarwanda",
    "Kirghiz",
    "Korean",
    "Kurdish",
    "Kurmanji",
    "Latin",
    "Lingala",
    "Luyia",
    "Macedonian",
    "Malay",
    "Malayalam",
    "Maltese",
    "Maranao",
    "Marathi",
    "Nepali",
    "Norwegian",
    "Oromo",
    "Panjabi",
    "Persian",
    "Polish",
    "Portuguese",
    "Pushto",
    "Romanian",
    "Rundi",
    "Russian",
    "Serbian",
    "Shona",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Sotho",
    "Spanish",
    "Swahili",
    "Swedish",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Turkish",
    "Twi",
    "Uighur",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Vietnamese",
    "Xhosa",
    "Yau",
    "Yoruba",
    "Zulu",
  ];
  
  export const quranLanguageVersions: Record<string, string[]> = {
    Achinese: [],
    Afar: [],
    Afrikaans: [],
    Albanian: ["la", "lad"],
    Amharic: ["la"],
    Arabic: ["la", "lad"],
    Assamese: ["la", "lad"],
    Azerbaijani: ["la"],
    Bambara: [],
    Bengali: ["la", "lad"],
    Berber: ["la"],
    Bosnian: ["la"],
    Bulgarian: ["la", "lad"],
    Burmese: [],
    Catalan: ["la"],
    Chichewa: [],
    Chinese_Simplified: ["la", "lad"],
    Chinese_Traditional: ["la", "lad"],
    Croatian: ["la"],
    Czech: ["la"],
    Dagbani: [],
    Dari: ["la", "lad"],
    Danish: [],
    Divehi: [],
    Dutch: [],
    English: [],
    Esperanto: [],
    Filipino: [],
    Finnish: ["la"],
    French: ["la"],
    Fulah: [],
    Ganda: [],
    German: ["la"],
    Gujarati: ["la", "lad"],
    Hausa: ["la"],
    Hebrew: [],
    Hindi: ["la"],
    Hungarian: ["la"],
    Indonesian: [],
    Iranun: [],
    Italian: ["la"],
    Japanese: ["la", "lad"],
    Javanese: ["la"],
    Kannada: ["la", "lad"],
    Kazakh: ["la", "lad"],
    Kendayan: [],
    Khmer: ["la"],
    Kinyarwanda: [],
    Kirghiz: ["la", "lad"],
    Korean: ["la"],
    Kurdish: [],
    Kurmanji: ["la"],
    Latin: [],
    Lingala: [],
    Luyia: [],
    Macedonian: ["la", "lad"],
    Malay: [],
    Malayalam: ["la", "lad"],
    Maltese: ["la"],
    Maranao: [],
    Marathi: ["la", "lad"],
    Nepali: ["la", "lad"],
    Norwegian: ["la"],
    Oromo: [],
    Panjabi: ["la", "lad"],
    Persian: [],
    Polish: ["la"],
    Portuguese: ["la"],
    Pushto: [],
    Romanian: ["la"],
    Rundi: [],
    Russian: ["la"],
    Serbian: [],
    Shona: [],
    Sindhi: [],
    Sinhala: ["la", "lad"],
    Slovak: [],
    Sotho: [],
    Spanish: ["la"],
    Swahili: [],
    Swedish: [],
    Tajik: ["la", "lad"],
    Tamil: ["la", "lad"],
    Tatar: [],
    Telugu: ["la", "lad"],
    Thai: ["la", "lad"],
    Turkish: ["la"],
    Twi: [],
    Uighur: [],
    Ukrainian: ["la"],
    Urdu: ["la"],
    Uzbek: [],
    Vietnamese: ["la"],
    Xhosa: [],
    Yau: ["la"],
    Yoruba: ["la"],
    Zulu: [],
  };
  
  // Hadith --
  export const hadithLanguages = ["english", "arabic"];
  
  export const hadithBooks = {
    ABM_BOOKS: new Set(["abudawud", "bukhari", "muslim"]),
    ITN_BOOKS: new Set(["ibnmajah", "tirmidhi", "nasai"]),
    ALL_BOOKS: new Set([
      "abudawud",
      "bukhari",
      "muslim",
      "ibnmajah",
      "tirmidhi",
      "nasai",
    ]),
  };